apiVersion: v1
appVersion: "2.0.0"
description: A Helm chart for Odoo Enterprise Enhanced.
name: odoo-ent-enhanced
icon: https://www.saastools.xyz/wp-content/uploads/Logo-Cloud-Services-2048.png
version: 2.0.0
