apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ template "postgres.fullname" . }}
  labels:
    app: postgres
    name: {{ template "postgres.name" . }}
spec:
  selector:
    matchLabels:
      app: postgres
      name: {{ template "postgres.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        name: {{ template "postgres.name" . }}
    spec:
      initContainers:
      - name: initfilepass
        image: alpine/git:1.0.7
        command:
        - sh
        - /etc/initsh-configmap/initpass.postgres.sh
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.username }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-postgres-{{ template "postgres.fullname" . }}
              key: pass
        volumeMounts:
        - mountPath: /home/postgresmetadata
          name: postgresmetadata
        - mountPath: /etc/initsh-configmap
          name: initsh-configmap
      containers:
      - name: postgres
        image: postgres:{{ .Values.postgresql.version }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.username }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-postgres-{{ template "postgres.fullname" . }}
              key: pass
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgresql
        - mountPath: /etc/initsh-configmap
          name: initsh-configmap
        workingDir: /etc/initsh-configmap
      volumes:
      - hostPath:
          path: {{ .Values.postgresql.hostpatch }}/data/
          type: DirectoryOrCreate
        name: postgresql
      - hostPath:
          path: {{ .Values.postgresql.hostpatch }}/metadata/
          type: DirectoryOrCreate
        name: postgresmetadata
      - configMap:
          name: configmap-{{ template "postgres.fullname" . }}
        name: initsh-configmap
