apiVersion: v1
kind: Service
metadata:
  name: service-{{ template "postgres.fullname" . }}
  labels:
    app: postgres
    name: {{ template "postgres.name" . }}
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
    name: {{ template "postgres.name" . }}